spring.application.name=proxiserve
# MongoDB Local (à adapter pour Docker/Atlas plus tard)
spring.data.mongodb.uri=mongodb://localhost:27017/artisanconnect


logging.level.org.springframework.data.mongodb=DEBUG
spring.security.user.name=admin
spring.security.user.password=admin




#jwt.secret=yourSuperSecretKeyThatIsAtLeast32BytesLong
#jwt.expiration=86400000

jwt.secret=xazLuNPWjNLwgO0TKUb5F0P2GFrUoMgurB65V2fYSECGIN/UvPzymozlbwt2kZR83eETCvyy14GCaS7mvoRzNA==
jwt.expiration=86400000  
# 1 jour en millisecondes

server.port=8080
