spring.application.name=proxiserve
# MongoDB Local (à adapter pour Docker/Atlas plus tard)
spring.data.mongodb.uri=mongodb://localhost:27017/artisanconnect


logging.level.org.springframework.data.mongodb=DEBUG
spring.security.user.name=admin
spring.security.user.password=admin




#jwt.secret=yourSuperSecretKeyThatIsAtLeast32BytesLong
#jwt.expiration=86400000

jwt.secret=iEqF6/7IGv1bHCjknt4afiEu7TIFxLOrX6yHobOBQMzCGlVItKW9W5PvPStvf27bQnL6zd74e6IggaaG9zLNzg==
jwt.expiration=86400000
# 1 mn = 60000 ms

server.port=8080