spring.application.name=proxiserve
# MongoDB Local 
spring.data.mongodb.uri=*****

logging.level.org.springframework.data.mongodb=DEBUG
spring.security.user.name=*****
spring.security.user.password=****


jwt.secret=a7rz/lF39+P8ZRrljTiEX7fkY0qGycCUocGXrax+qKv1JRqhGbzTO7yMqUoP5DAH4+txc0XIPcJDfQ3qf7/s7g==
jwt.expiration=86400000


spring.mvc.pathmatch.matching-strategy=ant-path-matcher

server.port=****
server.ssl.key-store=****
server.ssl.key-store-password=****
server.ssl.key-store-type=*****
server.ssl.key-alias=*****

# Configuration de l'email
spring.mail.host=smtp.gmail.com
spring.mail.port=****
spring.mail.username=******
spring.mail.password=*******
spring.mail.properties.mail.smtp.auth=*****
spring.mail.properties.mail.smtp.starttls.enable=****



# configurer cloudinary
cloudinary.cloud-name=proxiserve
cloudinary.api-key=311667947958616
cloudinary.api-secret=8P2-iIPP-2BBOPQxgsLwe7btZng
